[General]
name=hacker-theme
description=A hacker theme for SDDM with matrix digital rain effect.
author=Qaddoumi
forkauthor=iusepenguin
websiteoriginal=https://github.com/Qaddoumi/sddm-hacker-theme
license=MIT
version=1.0
background=assets/background.png
fontfamily=JetBrainsMono Nerd Font Propo
type=color
color=#00ff9c
fontsize=14
qtversion=6
cursortheme=capitaine-cursors
